# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diet.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_diet(object):
    def setupUi(self, diet):
        diet.setObjectName("diet")
        diet.resize(1227, 873)
        self.horizontalLayout = QtWidgets.QHBoxLayout(diet)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.side_nav_bar = QtWidgets.QListWidget(diet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.side_nav_bar.sizePolicy().hasHeightForWidth())
        self.side_nav_bar.setSizePolicy(sizePolicy)
        self.side_nav_bar.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.side_nav_bar.setFont(font)
        self.side_nav_bar.setStyleSheet("QListWidget{\n"
"background: rgb(63, 63, 63); \n"
"color:rgb(122, 122, 122);\n"
"border: none;\n"
"\n"
"}\n"
"QListWidget::item { \n"
"margin: 10px;\n"
"padding-top: 20px;\n"
"padding-left: 40px;\n"
"}\n"
"QListWidget::item::icon { \n"
"size: 10px;\n"
"}\n"
"")
        self.side_nav_bar.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.side_nav_bar.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.side_nav_bar.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.side_nav_bar.setAutoScroll(False)
        self.side_nav_bar.setProperty("showDropIndicator", True)
        self.side_nav_bar.setIconSize(QtCore.QSize(50, 30))
        self.side_nav_bar.setObjectName("side_nav_bar")
        item = QtWidgets.QListWidgetItem()
        icon = QtGui.QIcon.fromTheme("sidebar_icon")
        item.setIcon(icon)
        self.side_nav_bar.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon = QtGui.QIcon.fromTheme("sidebar_icon")
        item.setIcon(icon)
        self.side_nav_bar.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon = QtGui.QIcon.fromTheme("sidebar_icon")
        item.setIcon(icon)
        self.side_nav_bar.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon = QtGui.QIcon.fromTheme("sidebar_icon")
        item.setIcon(icon)
        self.side_nav_bar.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon = QtGui.QIcon.fromTheme("sidebar_icon")
        item.setIcon(icon)
        self.side_nav_bar.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon = QtGui.QIcon.fromTheme("sidebar_icon")
        item.setIcon(icon)
        self.side_nav_bar.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        icon = QtGui.QIcon.fromTheme("sidebar_icon")
        item.setIcon(icon)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.side_nav_bar.addItem(item)
        self.horizontalLayout.addWidget(self.side_nav_bar)
        self.scrollArea_4 = QtWidgets.QScrollArea(diet)
        self.scrollArea_4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(60)
        sizePolicy.setHeightForWidth(self.scrollArea_4.sizePolicy().hasHeightForWidth())
        self.scrollArea_4.setSizePolicy(sizePolicy)
        self.scrollArea_4.setMinimumSize(QtCore.QSize(500, 0))
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.diet_scroll_bar = QtWidgets.QWidget()
        self.diet_scroll_bar.setGeometry(QtCore.QRect(0, -13, 1396, 858))
        self.diet_scroll_bar.setObjectName("diet_scroll_bar")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.diet_scroll_bar)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.diet_content = QtWidgets.QFrame(self.diet_scroll_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diet_content.sizePolicy().hasHeightForWidth())
        self.diet_content.setSizePolicy(sizePolicy)
        self.diet_content.setStyleSheet("QFrame{\n"
"background-color: rgb(255, 255, 255);\n"
"color:rgb(62, 62, 62);\n"
"border: none;\n"
"\n"
"}")
        self.diet_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.diet_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.diet_content.setObjectName("diet_content")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.diet_content)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setSpacing(0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.diet_headline = QtWidgets.QLabel(self.diet_content)
        self.diet_headline.setStyleSheet("QLabel{\n"
"background:rgb(218, 0, 0); \n"
"color:rgb(59, 59, 59);\n"
"border: none;\n"
"}")
        self.diet_headline.setIndent(40)
        self.diet_headline.setObjectName("diet_headline")
        self.verticalLayout_25.addWidget(self.diet_headline)
        self.add_and_search_siet = QtWidgets.QFrame(self.diet_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.add_and_search_siet.sizePolicy().hasHeightForWidth())
        self.add_and_search_siet.setSizePolicy(sizePolicy)
        self.add_and_search_siet.setMinimumSize(QtCore.QSize(50, 50))
        self.add_and_search_siet.setStyleSheet("")
        self.add_and_search_siet.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.add_and_search_siet.setFrameShadow(QtWidgets.QFrame.Raised)
        self.add_and_search_siet.setObjectName("add_and_search_siet")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.add_and_search_siet)
        self.horizontalLayout_27.setContentsMargins(30, 30, 30, 30)
        self.horizontalLayout_27.setSpacing(20)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.search_food = QtWidgets.QGroupBox(self.add_and_search_siet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.search_food.sizePolicy().hasHeightForWidth())
        self.search_food.setSizePolicy(sizePolicy)
        self.search_food.setStyleSheet("background: rgb(222, 222, 222); \n"
"")
        self.search_food.setTitle("")
        self.search_food.setObjectName("search_food")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.search_food)
        self.gridLayout_2.setContentsMargins(30, 40, 30, 40)
        self.gridLayout_2.setHorizontalSpacing(20)
        self.gridLayout_2.setVerticalSpacing(12)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.food_database = QtWidgets.QTableView(self.search_food)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.food_database.setFont(font)
        self.food_database.setStyleSheet("border: none;\n"
"background-color: rgb(255, 255, 255);")
        self.food_database.setObjectName("food_database")
        self.gridLayout_2.addWidget(self.food_database, 2, 0, 1, 2)
        self.search_food_2 = QtWidgets.QLineEdit(self.search_food)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.search_food_2.setFont(font)
        self.search_food_2.setStyleSheet("border: none;\n"
"background-color: rgb(255, 255, 255);")
        self.search_food_2.setText("")
        self.search_food_2.setClearButtonEnabled(False)
        self.search_food_2.setObjectName("search_food_2")
        self.gridLayout_2.addWidget(self.search_food_2, 1, 0, 1, 2)
        self.select_food_label = QtWidgets.QLabel(self.search_food)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.select_food_label.setFont(font)
        self.select_food_label.setAlignment(QtCore.Qt.AlignCenter)
        self.select_food_label.setObjectName("select_food_label")
        self.gridLayout_2.addWidget(self.select_food_label, 0, 0, 1, 2)
        self.calories_line = QtWidgets.QLabel(self.search_food)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.calories_line.setFont(font)
        self.calories_line.setStyleSheet("border: none;\n"
"background: rgb(222, 222, 222); \n"
"color:rgb(0, 0, 0);\n"
"")
        self.calories_line.setObjectName("calories_line")
        self.gridLayout_2.addWidget(self.calories_line, 5, 0, 1, 1)
        self.calories_output = QtWidgets.QLineEdit(self.search_food)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.calories_output.setFont(font)
        self.calories_output.setStyleSheet("border: none;\n"
"background-color: rgb(255, 255, 255);")
        self.calories_output.setObjectName("calories_output")
        self.gridLayout_2.addWidget(self.calories_output, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.search_food)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("border: none;\n"
"background: rgb(222, 222, 222); \n"
"color:rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1)
        self.portion_lne = QtWidgets.QLabel(self.search_food)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.portion_lne.setFont(font)
        self.portion_lne.setStyleSheet("border: none;\n"
"background: rgb(222, 222, 222); \n"
"color:rgb(0, 0, 0);\n"
"")
        self.portion_lne.setObjectName("portion_lne")
        self.gridLayout_2.addWidget(self.portion_lne, 4, 0, 1, 1)
        self.portion_input = QtWidgets.QLineEdit(self.search_food)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.portion_input.setFont(font)
        self.portion_input.setStyleSheet("border: none;\n"
"background-color: rgb(255, 255, 255);")
        self.portion_input.setObjectName("portion_input")
        self.gridLayout_2.addWidget(self.portion_input, 4, 1, 1, 1)
        self.add_exercise_2 = QtWidgets.QPushButton(self.search_food)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.add_exercise_2.setFont(font)
        self.add_exercise_2.setObjectName("add_exercise_2")
        self.gridLayout_2.addWidget(self.add_exercise_2, 7, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.search_food)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setStyleSheet("border: none;\n"
"background-color: rgb(255, 255, 255);\n"
"height:37px\n"
"\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 3, 1, 1, 1)
        self.horizontalLayout_27.addWidget(self.search_food)
        self.add_food_box = QtWidgets.QGroupBox(self.add_and_search_siet)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.add_food_box.sizePolicy().hasHeightForWidth())
        self.add_food_box.setSizePolicy(sizePolicy)
        self.add_food_box.setStyleSheet("background: rgb(222, 222, 222); \n"
"")
        self.add_food_box.setTitle("")
        self.add_food_box.setObjectName("add_food_box")
        self.gridLayout = QtWidgets.QGridLayout(self.add_food_box)
        self.gridLayout.setContentsMargins(30, 200, 30, 200)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.search_food_label = QtWidgets.QLabel(self.add_food_box)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.search_food_label.setFont(font)
        self.search_food_label.setObjectName("search_food_label")
        self.gridLayout.addWidget(self.search_food_label, 0, 0, 1, 3)
        self.name_line = QtWidgets.QLabel(self.add_food_box)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.name_line.setFont(font)
        self.name_line.setStyleSheet("border: none;\n"
"background: rgb(222, 222, 222); \n"
"color:rgb(0, 0, 0);\n"
"")
        self.name_line.setObjectName("name_line")
        self.gridLayout.addWidget(self.name_line, 1, 0, 1, 1)
        self.name_input = QtWidgets.QLineEdit(self.add_food_box)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.name_input.setFont(font)
        self.name_input.setStyleSheet("border: none;\n"
"background-color: rgb(255, 255, 255);")
        self.name_input.setText("")
        self.name_input.setPlaceholderText("")
        self.name_input.setObjectName("name_input")
        self.gridLayout.addWidget(self.name_input, 1, 1, 1, 2)
        self.calories_input_label = QtWidgets.QLabel(self.add_food_box)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.calories_input_label.setFont(font)
        self.calories_input_label.setStyleSheet("border: none;\n"
"background: rgb(222, 222, 222); \n"
"color:rgb(0, 0, 0);\n"
"")
        self.calories_input_label.setObjectName("calories_input_label")
        self.gridLayout.addWidget(self.calories_input_label, 2, 0, 1, 2)
        self.calories_input = QtWidgets.QLineEdit(self.add_food_box)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.calories_input.setFont(font)
        self.calories_input.setStyleSheet("border: none;\n"
"background-color: rgb(255, 255, 255);")
        self.calories_input.setPlaceholderText("")
        self.calories_input.setObjectName("calories_input")
        self.gridLayout.addWidget(self.calories_input, 2, 2, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.add_food_box)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_34.setFont(font)
        self.label_34.setScaledContents(False)
        self.label_34.setWordWrap(True)
        self.label_34.setObjectName("label_34")
        self.gridLayout.addWidget(self.label_34, 3, 0, 1, 3)
        self.add_food = QtWidgets.QPushButton(self.add_food_box)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.add_food.setFont(font)
        self.add_food.setObjectName("add_food")
        self.gridLayout.addWidget(self.add_food, 4, 1, 1, 2)
        self.horizontalLayout_27.addWidget(self.add_food_box)
        self.verticalLayout_25.addWidget(self.add_and_search_siet)
        self.horizontalLayout_16.addWidget(self.diet_content)
        self.scrollArea_4.setWidget(self.diet_scroll_bar)
        self.horizontalLayout.addWidget(self.scrollArea_4)

        self.retranslateUi(diet)
        QtCore.QMetaObject.connectSlotsByName(diet)

    def retranslateUi(self, diet):
        _translate = QtCore.QCoreApplication.translate
        diet.setWindowTitle(_translate("diet", "Form"))
        __sortingEnabled = self.side_nav_bar.isSortingEnabled()
        self.side_nav_bar.setSortingEnabled(False)
        item = self.side_nav_bar.item(0)
        item.setText(_translate("diet", " Home"))
        item = self.side_nav_bar.item(1)
        item.setText(_translate("diet", " Profile"))
        item = self.side_nav_bar.item(2)
        item.setText(_translate("diet", " Goal"))
        item = self.side_nav_bar.item(3)
        item.setText(_translate("diet", " Exercise"))
        item = self.side_nav_bar.item(4)
        item.setText(_translate("diet", " Diet"))
        item = self.side_nav_bar.item(5)
        item.setText(_translate("diet", " Group"))
        item = self.side_nav_bar.item(6)
        item.setText(_translate("diet", " Log out"))
        self.side_nav_bar.setSortingEnabled(__sortingEnabled)
        self.diet_headline.setText(_translate("diet", "<html><head/><body><p><span style=\" font-family:\'Segoe UI\'; font-size:36pt;\">Diet</span></p></body></html>"))
        self.search_food_2.setPlaceholderText(_translate("diet", "Search for food..."))
        self.select_food_label.setText(_translate("diet", "Select your food database by name"))
        self.calories_line.setText(_translate("diet", "Calories"))
        self.label.setText(_translate("diet", "Food Name"))
        self.portion_lne.setText(_translate("diet", "Portion (g)"))
        self.add_exercise_2.setText(_translate("diet", "Add Food"))
        self.search_food_label.setText(_translate("diet", "Cannot find food you are looking for? "))
        self.name_line.setText(_translate("diet", "Name"))
        self.calories_input_label.setText(_translate("diet", "Calories (per 100g)"))
        self.label_34.setText(_translate("diet", "If you know how many calories the food contains in 100g (e.g. cooked chicken breast, 36kcal per 100g), manually enter that value above."))
        self.add_food.setText(_translate("diet", "Add New Food"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    diet = QtWidgets.QWidget()
    ui = Ui_diet()
    ui.setupUi(diet)
    diet.show()
    sys.exit(app.exec_())

