# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exerciseView.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_exercise_page(object):
    def __init__(self, exercise_page, table):
        self.setupUi(exercise_page,table)

    def setupUi(self, exercise_page, table):
        exercise_page.setObjectName("exercise_page")
        exercise_page.resize(1365, 826)
        self.horizontalLayout = QtWidgets.QHBoxLayout(exercise_page)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(exercise_page)
        self.scrollArea.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(60)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(500, 0))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea_4")
        self.exercise_scroll_area = QtWidgets.QWidget()
        self.exercise_scroll_area.setGeometry(QtCore.QRect(0, 0, 1344, 838))
        self.exercise_scroll_area.setObjectName("exercise_scroll_area")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.exercise_scroll_area)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.exercise_frame = QtWidgets.QFrame(self.exercise_scroll_area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exercise_frame.sizePolicy().hasHeightForWidth())
        self.exercise_frame.setSizePolicy(sizePolicy)
        self.exercise_frame.setStyleSheet("QFrame{\n"
"background-color: rgb(255, 255, 255);\n"
"color:rgb(62, 62, 62);\n"
"border: none;\n"
"\n"
"}")
        self.exercise_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.exercise_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.exercise_frame.setObjectName("exercise_frame")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.exercise_frame)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setSpacing(0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.exercise_headtitle = QtWidgets.QLabel(self.exercise_frame)
        self.exercise_headtitle.setStyleSheet("QLabel{\n"
"background:rgb(218, 0, 0); \n"
"color:rgb(59, 59, 59);\n"
"border: none;\n"
"}")
        self.exercise_headtitle.setIndent(40)
        self.exercise_headtitle.setObjectName("exercise_headtitle")
        self.verticalLayout_25.addWidget(self.exercise_headtitle)
        self.exercise_content = QtWidgets.QFrame(self.exercise_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.exercise_content.sizePolicy().hasHeightForWidth())
        self.exercise_content.setSizePolicy(sizePolicy)
        self.exercise_content.setMinimumSize(QtCore.QSize(50, 50))
        self.exercise_content.setStyleSheet("")
        self.exercise_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.exercise_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.exercise_content.setObjectName("exercise_content")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.exercise_content)
        self.horizontalLayout_27.setContentsMargins(30, 30, 30, 30)
        self.horizontalLayout_27.setSpacing(20)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.search_exercise = QtWidgets.QGroupBox(self.exercise_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.search_exercise.sizePolicy().hasHeightForWidth())
        self.search_exercise.setSizePolicy(sizePolicy)
        self.search_exercise.setStyleSheet("background: rgb(222, 222, 222); \n"
"")
        self.search_exercise.setTitle("")
        self.search_exercise.setObjectName("search_exercise")
        self.gridLayout = QtWidgets.QGridLayout(self.search_exercise)
        self.gridLayout.setContentsMargins(30, 40, 30, 40)
        self.gridLayout.setHorizontalSpacing(20)
        self.gridLayout.setVerticalSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.exercise_table = QtWidgets.QTableView(self.search_exercise)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exercise_table.setFont(font)
        self.exercise_table.setStyleSheet("border: none;\n"
"background-color: rgb(255, 255, 255);")
        self.exercise_table.setObjectName("exercise_table")
        self.exercise_table.setModel(table)  # At initialisation, the proxyModel is the model itself
        self.exercise_table.horizontalHeader().setSectionResizeMode(0,QtWidgets.QHeaderView.Stretch)
        self.exercise_table.horizontalHeader().setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeToContents)
        self.exercise_table.verticalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Interactive)
        self.gridLayout.addWidget(self.exercise_table, 2, 0, 1, 2)
        self.durationLabel_6 = QtWidgets.QLabel(self.search_exercise)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.durationLabel_6.setFont(font)
        self.durationLabel_6.setStyleSheet("background: rgb(222, 222, 222); \n"
"color:rgb(0, 0, 0);\n"
"border: none;\n"
"")
        self.durationLabel_6.setObjectName("durationLabel_6")
        self.gridLayout.addWidget(self.durationLabel_6, 4, 0, 1, 1)
        self.search_info = QtWidgets.QLabel(self.search_exercise)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.search_info.setFont(font)
        self.search_info.setAlignment(QtCore.Qt.AlignCenter)
        self.search_info.setObjectName("search_info")
        self.gridLayout.addWidget(self.search_info, 0, 0, 1, 2)
        self.add_calories_2 = QtWidgets.QLineEdit(self.search_exercise)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.add_calories_2.setFont(font)
        self.add_calories_2.setStyleSheet("border: none;\n"
"background-color: rgb(255, 255, 255);")
        self.add_calories_2.setObjectName("add_calories_2")
        self.gridLayout.addWidget(self.add_calories_2, 5, 1, 1, 1)
        self.duration_input = QtWidgets.QLineEdit(self.search_exercise)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.duration_input.setFont(font)
        self.duration_input.setStyleSheet("border: none;\n"
"background-color: rgb(255, 255, 255);")
        self.duration_input.setText("")
        self.duration_input.setObjectName("duration_input")
        self.gridLayout.addWidget(self.duration_input, 4, 1, 1, 1)
        self.search_input = QtWidgets.QLineEdit(self.search_exercise)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.search_input.setFont(font)
        self.search_input.setStyleSheet("border: none;\n"
"background-color: rgb(255, 255, 255);")
        self.search_input.setText("")
        self.search_input.setObjectName("search_input")
        self.gridLayout.addWidget(self.search_input, 1, 0, 1, 2)
        self.calories_label_2 = QtWidgets.QLabel(self.search_exercise)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.calories_label_2.setFont(font)
        self.calories_label_2.setStyleSheet("border: none;\n"
"background: rgb(222, 222, 222); \n"
"color:rgb(0, 0, 0);\n"
"")
        self.calories_label_2.setObjectName("calories_label_2")
        self.gridLayout.addWidget(self.calories_label_2, 5, 0, 1, 1)
        self.add_exercise_2 = QtWidgets.QPushButton(self.search_exercise)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.add_exercise_2.setFont(font)
        self.add_exercise_2.setObjectName("add_exercise_2")
        self.gridLayout.addWidget(self.add_exercise_2, 6, 0, 1, 2)
        self.exerciseName_2 = QtWidgets.QLineEdit(self.search_exercise)
        self.exerciseName_2.setStyleSheet("border: none;\n"
"background-color: rgb(255, 255, 255);\n"
"height:35px\n"
"\n"
"")
        self.exerciseName_2.setObjectName("exerciseName_2")
        self.gridLayout.addWidget(self.exerciseName_2, 3, 1, 1, 1)
        self.exerciseName = QtWidgets.QLabel(self.search_exercise)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.exerciseName.setFont(font)
        self.exerciseName.setObjectName("exerciseName")
        self.gridLayout.addWidget(self.exerciseName, 3, 0, 1, 1)
        self.horizontalLayout_27.addWidget(self.search_exercise)
        self.add_exercise = QtWidgets.QGroupBox(self.exercise_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.add_exercise.sizePolicy().hasHeightForWidth())
        self.add_exercise.setSizePolicy(sizePolicy)
        self.add_exercise.setStyleSheet("background: rgb(222, 222, 222); \n"
"")
        self.add_exercise.setTitle("")
        self.add_exercise.setObjectName("add_exercise")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.add_exercise)
        self.gridLayout_2.setContentsMargins(30, 200, 30, 200)
        self.gridLayout_2.setHorizontalSpacing(20)
        self.gridLayout_2.setVerticalSpacing(15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.durationLabel_5 = QtWidgets.QLabel(self.add_exercise)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.durationLabel_5.setFont(font)
        self.durationLabel_5.setStyleSheet("background: rgb(222, 222, 222); \n"
"color:rgb(0, 0, 0);\n"
"border: none;\n"
"")
        self.durationLabel_5.setObjectName("durationLabel_5")
        self.gridLayout_2.addWidget(self.durationLabel_5, 2, 0, 1, 1)
        self.calories_label = QtWidgets.QLabel(self.add_exercise)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.calories_label.setFont(font)
        self.calories_label.setStyleSheet("border: none;\n"
"background: rgb(222, 222, 222); \n"
"color:rgb(0, 0, 0);\n"
"")
        self.calories_label.setObjectName("calories_label")
        self.gridLayout_2.addWidget(self.calories_label, 3, 0, 1, 1)
        self.find_label_info = QtWidgets.QLabel(self.add_exercise)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.find_label_info.setFont(font)
        self.find_label_info.setObjectName("find_label_info")
        self.gridLayout_2.addWidget(self.find_label_info, 0, 0, 1, 2)
        self.info_label = QtWidgets.QLabel(self.add_exercise)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.info_label.setFont(font)
        self.info_label.setScaledContents(False)
        self.info_label.setWordWrap(True)
        self.info_label.setObjectName("info_label")
        self.gridLayout_2.addWidget(self.info_label, 4, 0, 1, 2)
        self.add_calories = QtWidgets.QLineEdit(self.add_exercise)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.add_calories.setFont(font)
        self.add_calories.setStyleSheet("border: none;\n"
"background-color: rgb(255, 255, 255);")
        self.add_calories.setObjectName("add_calories")
        self.gridLayout_2.addWidget(self.add_calories, 3, 1, 1, 1)
        self.durationLineEdit_5 = QtWidgets.QLineEdit(self.add_exercise)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.durationLineEdit_5.setFont(font)
        self.durationLineEdit_5.setStyleSheet("border: none;\n"
"background-color: rgb(255, 255, 255);")
        self.durationLineEdit_5.setText("")
        self.durationLineEdit_5.setObjectName("durationLineEdit_5")
        self.gridLayout_2.addWidget(self.durationLineEdit_5, 2, 1, 1, 1)
        self.add_exercise_3 = QtWidgets.QPushButton(self.add_exercise)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.add_exercise_3.setFont(font)
        self.add_exercise_3.setObjectName("add_exercise_3")
        self.gridLayout_2.addWidget(self.add_exercise_3, 5, 0, 1, 2)
        self.horizontalLayout_27.addWidget(self.add_exercise)
        self.verticalLayout_25.addWidget(self.exercise_content)
        self.horizontalLayout_16.addWidget(self.exercise_frame)
        self.scrollArea.setWidget(self.exercise_scroll_area)
        self.horizontalLayout.addWidget(self.scrollArea)

        self.retranslateUi(exercise_page)
        QtCore.QMetaObject.connectSlotsByName(exercise_page)

    def retranslateUi(self, exercise_page):
        _translate = QtCore.QCoreApplication.translate
        exercise_page.setWindowTitle(_translate("exercise_page", "Form"))
        self.exercise_headtitle.setText(_translate("exercise_page", "<html><head/><body><p><span style=\" font-family:\'Segoe UI\'; font-size:36pt;\">Exercise</span></p></body></html>"))
        self.durationLabel_6.setText(_translate("exercise_page", "Duration in minutes"))
        self.search_info.setText(_translate("exercise_page", "Search our exercise database by name"))
        self.search_input.setPlaceholderText(_translate("exercise_page", "Search for exercise..."))
        self.calories_label_2.setText(_translate("exercise_page", "Calories"))
        self.add_exercise_2.setText(_translate("exercise_page", "Add Exercise"))
        self.exerciseName.setText(_translate("exercise_page", "Exercise name"))
        self.durationLabel_5.setText(_translate("exercise_page", "Name"))
        self.calories_label.setText(_translate("exercise_page", "MET"))
        self.find_label_info.setText(_translate("exercise_page", "Cannot find exercise you are looking for? "))
        self.info_label.setText(_translate("exercise_page", "If you know how many calories you burned (e.g. from a machine at the gym), manually enter that value above."))
        self.add_exercise_3.setText(_translate("exercise_page", "Add New Exercise"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    exercise_page = QtWidgets.QWidget()
    ui = Ui_exercise_page()
    ui.setupUi(exercise_page)
    exercise_page.show()
    sys.exit(app.exec_())

