# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signin.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_signinWindow(object):
    def setupUi(self, signinWindow):
        signinWindow.setObjectName("signinWindow")
        signinWindow.resize(800, 596)
        signinWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(signinWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("background: rgb(243, 243, 243)")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stackedWidget.setLineWidth(100)
        self.stackedWidget.setObjectName("stackedWidget")
        self.Login = QtWidgets.QWidget()
        self.Login.setObjectName("Login")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Login)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame = QtWidgets.QFrame(self.Login)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame.setFont(font)
        self.frame.setStyleSheet("background:rgb(218, 0, 0); \n"
"color:rgb(59, 59, 59);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(30, 50, 30, 80)
        self.verticalLayout.setObjectName("verticalLayout")
        self.login_frame = QtWidgets.QFrame(self.frame)
        self.login_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_frame.setObjectName("login_frame")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.login_frame)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setHorizontalSpacing(10)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.create_account = QtWidgets.QPushButton(self.login_frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.create_account.setFont(font)
        self.create_account.setStyleSheet("background: rgb(222, 222, 222); \n"
"")
        self.create_account.setObjectName("create_account")
        self.gridLayout_8.addWidget(self.create_account, 1, 1, 1, 1)
        self.login_username = QtWidgets.QLineEdit(self.login_frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.login_username.setFont(font)
        self.login_username.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.login_username.setInputMask("")
        self.login_username.setText("")
        self.login_username.setObjectName("login_username")
        self.gridLayout_8.addWidget(self.login_username, 0, 0, 1, 1)
        self.login_password = QtWidgets.QLineEdit(self.login_frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.login_password.setFont(font)
        self.login_password.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.login_password.setInputMask("")
        self.login_password.setText("")
        self.login_password.setObjectName("login_password")
        self.gridLayout_8.addWidget(self.login_password, 0, 1, 1, 1)
        self.login = QtWidgets.QPushButton(self.login_frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.login.setFont(font)
        self.login.setStyleSheet("background: rgb(222, 222, 222); \n"
"")
        self.login.setObjectName("login")
        self.gridLayout_8.addWidget(self.login, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.login_frame)
        self.home_wall_2 = QtWidgets.QTextBrowser(self.frame)
        self.home_wall_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:none;")
        self.home_wall_2.setObjectName("home_wall_2")
        self.verticalLayout.addWidget(self.home_wall_2)
        self.gridLayout_4.addWidget(self.frame, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.Login)
        self.Register = QtWidgets.QWidget()
        self.Register.setObjectName("Register")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Register)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.input_frame = QtWidgets.QFrame(self.Register)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.input_frame.sizePolicy().hasHeightForWidth())
        self.input_frame.setSizePolicy(sizePolicy)
        self.input_frame.setMinimumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.input_frame.setFont(font)
        self.input_frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_frame.setObjectName("input_frame")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.input_frame)
        self.verticalLayout_22.setContentsMargins(100, 30, 100, 23)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.frame_3 = QtWidgets.QFrame(self.input_frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setHorizontalSpacing(0)
        self.gridLayout_5.setVerticalSpacing(7)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.name_label = QtWidgets.QLineEdit(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name_label.setFont(font)
        self.name_label.setStyleSheet("background:rgb(222, 222, 222); \n"
"color:rgb(62, 62, 62);")
        self.name_label.setReadOnly(True)
        self.name_label.setObjectName("name_label")
        self.gridLayout_5.addWidget(self.name_label, 0, 0, 1, 1)
        self.dob_label = QtWidgets.QLineEdit(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dob_label.setFont(font)
        self.dob_label.setStyleSheet("background:rgb(222, 222, 222); \n"
"color:rgb(62, 62, 62);")
        self.dob_label.setReadOnly(True)
        self.dob_label.setObjectName("dob_label")
        self.gridLayout_5.addWidget(self.dob_label, 1, 0, 1, 1)
        self.name = QtWidgets.QLineEdit(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name.setFont(font)
        self.name.setInputMask("")
        self.name.setText("")
        self.name.setObjectName("name")
        self.gridLayout_5.addWidget(self.name, 0, 1, 1, 1)
        self.dob = QtWidgets.QDateEdit(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dob.setFont(font)
        self.dob.setObjectName("dob")
        self.gridLayout_5.addWidget(self.dob, 1, 1, 1, 1)
        self.gender_label = QtWidgets.QLineEdit(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gender_label.setFont(font)
        self.gender_label.setStyleSheet("background:rgb(222, 222, 222); \n"
"color:rgb(62, 62, 62);")
        self.gender_label.setReadOnly(True)
        self.gender_label.setObjectName("gender_label")
        self.gridLayout_5.addWidget(self.gender_label, 2, 0, 1, 1)
        self.height_label = QtWidgets.QLineEdit(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.height_label.setFont(font)
        self.height_label.setStyleSheet("background:rgb(222, 222, 222); \n"
"color:rgb(62, 62, 62);")
        self.height_label.setReadOnly(True)
        self.height_label.setObjectName("height_label")
        self.gridLayout_5.addWidget(self.height_label, 3, 0, 1, 1)
        self.gender = QtWidgets.QComboBox(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gender.setFont(font)
        self.gender.setObjectName("gender")
        self.gender.addItem("")
        self.gender.addItem("")
        self.gender.addItem("")
        self.gridLayout_5.addWidget(self.gender, 2, 1, 1, 1)
        self.height = QtWidgets.QLineEdit(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.height.setFont(font)
        self.height.setInputMask("")
        self.height.setText("")
        self.height.setObjectName("height")
        self.gridLayout_5.addWidget(self.height, 3, 1, 1, 1)
        self.weight_label = QtWidgets.QLineEdit(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.weight_label.setFont(font)
        self.weight_label.setStyleSheet("background:rgb(222, 222, 222); \n"
"color:rgb(62, 62, 62);")
        self.weight_label.setReadOnly(True)
        self.weight_label.setObjectName("weight_label")
        self.gridLayout_5.addWidget(self.weight_label, 4, 0, 1, 1)
        self.weight = QtWidgets.QLineEdit(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.weight.setFont(font)
        self.weight.setInputMask("")
        self.weight.setText("")
        self.weight.setObjectName("weight")
        self.gridLayout_5.addWidget(self.weight, 4, 1, 1, 1)
        self.username_label = QtWidgets.QLineEdit(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.username_label.setFont(font)
        self.username_label.setStyleSheet("background:rgb(222, 222, 222); \n"
"color:rgb(62, 62, 62);")
        self.username_label.setReadOnly(True)
        self.username_label.setObjectName("username_label")
        self.gridLayout_5.addWidget(self.username_label, 5, 0, 1, 1)
        self.password = QtWidgets.QLineEdit(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password.setFont(font)
        self.password.setInputMask("")
        self.password.setText("")
        self.password.setObjectName("password")
        self.gridLayout_5.addWidget(self.password, 6, 1, 1, 1)
        self.email_label = QtWidgets.QLineEdit(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.email_label.setFont(font)
        self.email_label.setStyleSheet("background:rgb(222, 222, 222); \n"
"color:rgb(62, 62, 62);")
        self.email_label.setReadOnly(True)
        self.email_label.setObjectName("email_label")
        self.gridLayout_5.addWidget(self.email_label, 7, 0, 1, 1)
        self.username = QtWidgets.QLineEdit(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.username.setFont(font)
        self.username.setInputMask("")
        self.username.setText("")
        self.username.setObjectName("username")
        self.gridLayout_5.addWidget(self.username, 5, 1, 1, 1)
        self.password_label = QtWidgets.QLineEdit(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password_label.setFont(font)
        self.password_label.setStyleSheet("background:rgb(222, 222, 222); \n"
"color:rgb(62, 62, 62);")
        self.password_label.setReadOnly(True)
        self.password_label.setObjectName("password_label")
        self.gridLayout_5.addWidget(self.password_label, 6, 0, 1, 1)
        self.email = QtWidgets.QLineEdit(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.email.setFont(font)
        self.email.setInputMask("")
        self.email.setText("")
        self.email.setObjectName("email")
        self.gridLayout_5.addWidget(self.email, 7, 1, 1, 1)
        self.verticalLayout_22.addWidget(self.frame_3)
        self.signup = QtWidgets.QPushButton(self.input_frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.signup.setFont(font)
        self.signup.setStyleSheet("background:rgb(222, 222, 222); \n"
"")
        self.signup.setObjectName("signup")
        self.verticalLayout_22.addWidget(self.signup)
        self.cancel = QtWidgets.QPushButton(self.input_frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cancel.setFont(font)
        self.cancel.setStyleSheet("background:rgb(222, 222, 222); \n"
"")
        self.cancel.setObjectName("cancel")
        self.verticalLayout_22.addWidget(self.cancel)
        self.gridLayout_2.addWidget(self.input_frame, 1, 0, 1, 1)
        self.header_frame = QtWidgets.QFrame(self.Register)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header_frame.sizePolicy().hasHeightForWidth())
        self.header_frame.setSizePolicy(sizePolicy)
        self.header_frame.setStyleSheet("QFrame{\n"
"background-color: rgb(255, 255, 255);\n"
"color:rgb(62, 62, 62);\n"
"border: none;\n"
"\n"
"}")
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.header_frame)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.register_header = QtWidgets.QLabel(self.header_frame)
        self.register_header.setStyleSheet("QLabel{\n"
"background:rgb(218, 0, 0); \n"
"color:rgb(59, 59, 59);\n"
"border: none;\n"
"}")
        self.register_header.setIndent(40)
        self.register_header.setObjectName("register_header")
        self.gridLayout_3.addWidget(self.register_header, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.header_frame, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.Register)
        self.gridLayout.addWidget(self.stackedWidget, 1, 0, 1, 1)
        signinWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(signinWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(signinWindow)

    def retranslateUi(self, signinWindow):
        _translate = QtCore.QCoreApplication.translate
        signinWindow.setWindowTitle(_translate("signinWindow", "MainWindow"))
        self.create_account.setText(_translate("signinWindow", "Register"))
        self.login_username.setPlaceholderText(_translate("signinWindow", "username"))
        self.login_password.setPlaceholderText(_translate("signinWindow", "password"))
        self.login.setText(_translate("signinWindow", "Login"))
        self.home_wall_2.setHtml(_translate("signinWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:20pt; font-weight:600; font-style:italic;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:26pt; font-weight:600; font-style:italic;\">&quot;\'</span><span style=\" font-family:\'AvenirNext-Regular\'; font-size:26pt; color:#303030; background-color:#ffffff;\">You must expect great things of yourself before you can do them.</span><span style=\" font-size:26pt; font-weight:600; font-style:italic;\">&quot;</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:20pt; font-weight:600; font-style:italic;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-style:italic;\">~ Michael Jordon</span></p></body></html>"))
        self.name_label.setText(_translate("signinWindow", "Name"))
        self.dob_label.setText(_translate("signinWindow", "Date of Birth"))
        self.name.setPlaceholderText(_translate("signinWindow", "name"))
        self.gender_label.setText(_translate("signinWindow", "Gender"))
        self.height_label.setText(_translate("signinWindow", "Heigth"))
        self.gender.setItemText(0, _translate("signinWindow", "Male"))
        self.gender.setItemText(1, _translate("signinWindow", "Female"))
        self.gender.setItemText(2, _translate("signinWindow", "Prefer not to say"))
        self.height.setPlaceholderText(_translate("signinWindow", "height"))
        self.weight_label.setText(_translate("signinWindow", "Weigth"))
        self.weight.setPlaceholderText(_translate("signinWindow", "weight"))
        self.username_label.setText(_translate("signinWindow", "Username"))
        self.password.setPlaceholderText(_translate("signinWindow", "password"))
        self.email_label.setText(_translate("signinWindow", "Email"))
        self.username.setPlaceholderText(_translate("signinWindow", "username"))
        self.password_label.setText(_translate("signinWindow", "Password"))
        self.email.setPlaceholderText(_translate("signinWindow", "email"))
        self.signup.setText(_translate("signinWindow", "Sign up"))
        self.cancel.setText(_translate("signinWindow", "Cancel"))
        self.register_header.setText(_translate("signinWindow", "<html><head/><body><p><span style=\" font-family:\'Segoe UI\'; font-size:36pt;\">Register</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    signinWindow = QtWidgets.QMainWindow()
    ui = Ui_signinWindow()
    ui.setupUi(signinWindow)
    signinWindow.show()
    sys.exit(app.exec_())
