# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signin.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLineEdit


class Ui_signinWindow(object):
    def setupUi(self, signinWindow):
        signinWindow.setObjectName("signinWindow")
        signinWindow.resize(802, 662)
        self.centralwidget = QtWidgets.QWidget(signinWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 801, 631))
        self.stackedWidget.setStyleSheet("background: rgb(243, 243, 243)")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stackedWidget.setLineWidth(100)
        self.stackedWidget.setObjectName("stackedWidget")
        self.Login = QtWidgets.QWidget()
        self.Login.setObjectName("Login")
        self.login_username = QtWidgets.QLineEdit(self.Login)
        self.login_username.setGeometry(QtCore.QRect(300, 30, 161, 41))
        self.login_username.setInputMask("")
        self.login_username.setText("")
        self.login_username.setObjectName("login_username")
        self.login_password = QtWidgets.QLineEdit(self.Login)
        self.login_password.setGeometry(QtCore.QRect(480, 30, 151, 41))
        self.login_password.setInputMask("")
        self.login_password.setText("")
        self.login_password.setObjectName("login_password")
        self.login_password.setEchoMode(QLineEdit.Password)
        self.login = QtWidgets.QPushButton(self.Login)
        self.login.setGeometry(QtCore.QRect(650, 30, 75, 23))
        self.login.setObjectName("login")
        self.home_wall = QtWidgets.QTextBrowser(self.Login)
        self.home_wall.setGeometry(QtCore.QRect(30, 120, 741, 391))
        self.home_wall.setObjectName("home_wall")
        self.create_account = QtWidgets.QPushButton(self.Login)
        self.create_account.setGeometry(QtCore.QRect(650, 60, 75, 23))
        self.create_account.setObjectName("create_account")
        self.stackedWidget.addWidget(self.Login)
        self.Register = QtWidgets.QWidget()
        self.Register.setObjectName("Register")
        self.username = QtWidgets.QLineEdit(self.Register)
        self.username.setGeometry(QtCore.QRect(80, 290, 161, 41))
        self.username.setInputMask("")
        self.username.setText("")
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(self.Register)
        self.password.setGeometry(QtCore.QRect(280, 290, 161, 41))
        self.password.setInputMask("")
        self.password.setText("")
        self.password.setObjectName("password")
        self.name = QtWidgets.QLineEdit(self.Register)
        self.name.setGeometry(QtCore.QRect(80, 120, 161, 41))
        self.name.setInputMask("")
        self.name.setText("")
        self.name.setObjectName("name")
        self.gender = QtWidgets.QComboBox(self.Register)
        self.gender.setGeometry(QtCore.QRect(280, 140, 69, 22))
        self.gender.setObjectName("gender")
        self.gender.addItem("")
        self.gender.addItem("")
        self.gender.addItem("")
        self.email = QtWidgets.QLineEdit(self.Register)
        self.email.setGeometry(QtCore.QRect(280, 190, 161, 41))
        self.email.setInputMask("")
        self.email.setText("")
        self.email.setObjectName("email")
        self.height = QtWidgets.QLineEdit(self.Register)
        self.height.setGeometry(QtCore.QRect(80, 370, 161, 41))
        self.height.setInputMask("")
        self.height.setText("")
        self.height.setObjectName("height")
        self.weight = QtWidgets.QLineEdit(self.Register)
        self.weight.setGeometry(QtCore.QRect(280, 370, 161, 41))
        self.weight.setInputMask("")
        self.weight.setText("")
        self.weight.setObjectName("weight")
        self.register_header = QtWidgets.QLabel(self.Register)
        self.register_header.setGeometry(QtCore.QRect(90, 30, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.register_header.setFont(font)
        self.register_header.setObjectName("register_header")
        self.cancel = QtWidgets.QPushButton(self.Register)
        self.cancel.setGeometry(QtCore.QRect(130, 490, 75, 23))
        self.cancel.setObjectName("cancel")
        #self.create_account.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(0))
        self.signup = QtWidgets.QPushButton(self.Register)
        self.signup.setGeometry(QtCore.QRect(300, 490, 71, 23))
        self.signup.setObjectName("signup")
        self.gender_label = QtWidgets.QLabel(self.Register)
        self.gender_label.setGeometry(QtCore.QRect(280, 120, 47, 13))
        self.gender_label.setObjectName("gender_label")
        self.dob_label = QtWidgets.QLabel(self.Register)
        self.dob_label.setGeometry(QtCore.QRect(80, 170, 71, 16))
        self.dob_label.setObjectName("dob_label")
        self.dob = QtWidgets.QDateEdit(self.Register)
        self.dob.setGeometry(QtCore.QRect(80, 190, 161, 41))
        self.dob.setObjectName("dob")
        self.stackedWidget.addWidget(self.Register)
        signinWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(signinWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 802, 21))
        self.menubar.setObjectName("menubar")
        signinWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(signinWindow)
        self.statusbar.setObjectName("statusbar")
        signinWindow.setStatusBar(self.statusbar)

        self.retranslateUi(signinWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(signinWindow)

    def retranslateUi(self, signinWindow):
        _translate = QtCore.QCoreApplication.translate
        signinWindow.setWindowTitle(_translate("signinWindow", "MainWindow"))
        self.login_username.setPlaceholderText(_translate("signinWindow", "username"))
        self.login_password.setPlaceholderText(_translate("signinWindow", "password"))
        self.login.setText(_translate("signinWindow", "Login"))
        self.home_wall.setHtml(_translate("signinWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-weight:600; font-style:italic;\">Never Give Up</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:20pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-style:italic;\">~ Hemal, CEO</span></p></body></html>"))
        self.create_account.setText(_translate("signinWindow", "Register"))
        self.username.setPlaceholderText(_translate("signinWindow", "username"))
        self.password.setPlaceholderText(_translate("signinWindow", "password"))
        self.name.setPlaceholderText(_translate("signinWindow", "name"))
        self.gender.setItemText(0, _translate("signinWindow", "male"))
        self.gender.setItemText(1, _translate("signinWindow", "female"))
        self.gender.setItemText(2, _translate("signinWindow", "Prefer not to say"))
        self.email.setPlaceholderText(_translate("signinWindow", "email"))
        self.height.setPlaceholderText(_translate("signinWindow", "height"))
        self.weight.setPlaceholderText(_translate("signinWindow", "weight"))
        self.register_header.setText(_translate("signinWindow", "Register"))
        self.cancel.setText(_translate("signinWindow", "Cancel"))
        self.signup.setText(_translate("signinWindow", "Sign up"))
        self.gender_label.setText(_translate("signinWindow", "Gender"))
        self.dob_label.setText(_translate("signinWindow", "Date of Birth"))
